apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smokeping-tailscale
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: smokeping
      port:
        name: http
  tls:
    - hosts:
        - ping
