apiVersion: v1
kind: Service
metadata:
  name: pinchflat
  labels:
    app: pinchflat
spec:
  type: ClusterIP
  ports:
    - port: 8945
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: pinchflat
