resources:
  - helm
  - bitwarden
  - secrets
  - dashboard
  - cnpg-system
  - mariadb-operator
  - databases
  - matrix
  #- gitlab-runner
  - immich
  - monitoring
  - pinchflat
  - smokeping
  - uptimekuma
  - donetick
  - gitea
