apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  labels:
    app: prometheus-deployment
spec:
  storageClassName: longhorn-default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "20Gi"
