apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: "24h"
  url: "https://helm.irsigler.cloud"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 10m
  chart:
    spec:
      chart: uptime-kuma
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
      interval: "1h"
  values:
    volume:
      storageClassName: longhorn-default
    image:
      tag: "2.0.2"
    externalDatabase:
      enabled: true
      hostname: mariadb-cluster.mariadb-operator.svc.cluster.local
      database: uptimekuma
      existingSecret: uptimekuma-mariadb-password
