apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uptimekuma-mariadb-password
spec:
  target:
    name: uptimekuma-mariadb-password
    deletionPolicy: Delete
    template:
      type: kubernetes.io/basic-auth
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: 4df95656-9f9c-4916-8e34-b3a200376365
        property: username
    - secretKey: password
      remoteRef:
        key: 4df95656-9f9c-4916-8e34-b3a200376365
        property: password
