apiVersion: v1
kind: Service
metadata:
  name: donetick
  namespace: donetick
spec:
  selector:
    app: donetick
  ports:
    - name: http
      port: 2021
      targetPort: 2021
      protocol: TCP
